name: prod-CI 

# manully trigger the job 

on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: 'enter image tag'     
        required: true
        default: 'v2.0.1'
        
# trigger the job on push for all branches except pre-prod 

  push:
    branches: 
      - 'feature**'
      - 'master'
  
  
jobs:
 Build-Push-To-GCR:

#choose the OS in which you want to trigger the job 

    runs-on: ubuntu-latest
#Environment variables
    env:
      HOSTNAME: us.gcr.io 
      PROJECT_ID: io1-homeservices-dev
      IMAGE_NAME: pro-xtra-ingestion-pub-sub #${{ github.event.repository.name }} 
      MAVEN_GOAL: clean install
      SLACK_CHANNEL: hello-see-log
      URL_GITACTION: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
      GIT_branch: ${GITHUB_REF##*/}
    steps:
    

# # post slack message that job is triggered 

      - name: Post to a Slack channel
        if: always()
        uses: slackapi/slack-github-action@v1.18.0
        with:
          channel-id: ${{ env.SLACK_CHANNEL }}
          slack-message:  ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.event.repository.name }} has started | check this out | ${{ github.URL_GITACTION }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

# checkout to barnch u manually trigger or to the branch with latest commit

      - uses: actions/checkout@v2

      - name: Set the GITHUB_ENVvalue
        run: |
          echo "IMAGE_NAME=$(cat ./pom.xml | grep "artifactId" | cut -d'>' -f2 | cut -d'<' -f1 | head -1)" >> $GITHUB_ENV 
          echo "TAG_NAME=$(cat ./pom.xml | grep "version" | cut -d'>' -f2 | cut -d'<' -f1 | head -1)" >> $GITHUB_ENV
          echo "${{ env.IMAGE_NAME }}" 
          echo "${{ env.TAG_NAME }}"    
# install java in VM
      
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
