name: javaversion

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '1.8'
          cache: 'maven'
          
      - name:  check java version
        run: |
          mvn -version
          java -version
