name: automatic-release 

# manully trigger the job 

on:
  push:
  
jobs:
 automatic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: send release request
        run: echo "${{ github.api_url }}/repos/${{ github.repository }}/releases"
      - name: send release request
        run: |
          curl -v -i -X POST -H "Content-Type:application/json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" ${{ github.api_url }}/repos/${{ github.repository }}/releases -d '{"tag_name":"v19.1.1","name": "v19.1.1","generate_release_notes":"true"}'

