name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          #java-version: '9.0.4'
          #maven-version: '3.6.2'
          java-version: '11'
          distribution: 'adopt'
      - name:  Maven version 
        run: |
          mvn -version
          java -version 
