name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '9.0.4'
          maven-version: '3.6.2'
      - name:  Maven version 
        run: |
          mvn -version
          java -version 
          mvn -version
          java -version 
