name: shell commands

on: [push]

jobs: 
  run-shell-command:
    runs-on: ubuntu_latest 
    steps:
      - name: echo a string
        run: echo "hi vinay"
      - name: multi line script
        run: |
          node -v
          npm -v
