
name: CI-build & push to GCR on chnages to develop & feature branch

# manully trigger the job 

on:
  workflow_dispatch:
    inputs:
      docker image tag:
        description: 'enter docker image version'     
        required: true
        default: '2.01'
        
# trigger the job on push below branches 

  #push:
      #branches: [develop, master, feature/*]
  

  
jobs:
 ci:

#choose the OS in which you want to trigger the job 

    runs-on: ubuntu-latest
    steps:
    
# checkout to barnch u manually trigger or to the branch with latest commit

      - uses: actions/checkout@v2
      
      
# install java in VM
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
# build artifact with maven 
  
      - name: Build with Maven
        run: mvn clean install
        
# build docker image

      - name: build docker image
        run: |
          cd ./account-service
          docker build -t us.gcr.io/io1-homeservices-dev/${{ github.event.repository.name }}:${{ github.event.inputs.docker image tag }} .
          docker images
          
      - name: Build with Maven
        run: docker images
         
         

        
 
