name: shell commands

on: [push]

jobs: 
  run-shell-command:
    runs_on: ubuntu_latest 
    step:
      - name: echo a string
        run: echo "hi vinay"
      -name: multi line script
       run: |
          node -v
          npm -v
