
name: feature branch  CI with maven

on:
  push:
    branches: [ master ]

jobs:
  build-java:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean install

      - name: present working directory 
        run: pwd
 
      - name: checking java version 
        run: java -version 
