
name: CI-build & push to GCR on chnages to develop & feature branch

on:
  workflow_dispatch:
  push:
      branches: [develop, master, feature/*]
  

  
jobs:
 ci:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        # run: mvn --batch-mode --update-snapshots verify
        run: mvn clean install

      - name: present working directory 
        run: pwd
 
      - name: checking java version 
        run: java -version 
        
         
      - name: changing directoey 
        run: |
         cd ./account-service
         pwd
         docker build -t hello/hello/hello:v2.0.1 .
         docker images
        
      - name: present working directory 
        run: pwd

      - name: maven version 
        run: mvn -v
        
      - name: docker version 
        run: docker --version
         
         

        
 
