
name: CI-Build and Push docker Image to Google Cloud Platform

# manully trigger the job 

on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: 'enter docker image version'     
        required: true
        default: '2.01'
        
# trigger the job on push below branches 

  #push:
      #branches: [develop, master, feature/*]
  
  
jobs:
 Build-Push-GCR:

#choose the OS in which you want to trigger the job 

    runs-on: ubuntu-latest
#Environment variables
    env:
      HOSTNAME: us.gcr.io
      PROJECT_ID: astute-cumulus-337508
      IMAGE_NAME: ${{ github.event.repository.name }}
      MAVEN_GOAL: clean install
      SLACK_CHANNEL: hello-see-log
    steps:
    
# checkout to barnch u manually trigger or to the branch with latest commit

      - uses: vinaygonchikar/checkout@v2
      
      
# install java in VM
      
      - name: Set up JDK 11
        uses: vinaygonchikar/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
# Build with Maven
  
      #- name: Build with Maven
        #run: mvn $MAVEN_GOAL
        
#Authentication to GCR
        
      #- uses: vinaygonchikar/setup-gcloud@master
        #with:
          #service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          #project_id: ${{ env.PROJECT_ID }}
          #export_default_credentials: true
          
# change path & build docker image
          
      #- name: build docker image
        #run: |
          #cd ./account-service
          #docker build -t $HOSTNAME/$PROJECT_ID/$IMAGE_NAME:${{ github.event.inputs.image-tag }} .
        
#configure docker use Google cloud while pushing image


      #- name: Configure Docker Client
        #run: |-
          #gcloud auth configure-docker --quiet
          #gcloud auth configure-docker $env.PROJECT_ID --quiet

          
# show all docker images in vm
          
      - name: docker image
        run: docker images
        
      - name: docker image
        run: |
          $GITHUB_ACTION	
          $GITHUB_ACTION_PATH
          $GITHUB_ACTION_REPOSITORY
          $GITHUB_ACTIONS
          $GITHUB_ACTOR
          $GITHUB_API_URL
          $GITHUB_BASE_REF
          $GITHUB_ENV	
          $GITHUB_EVENT_NAME	
          $GITHUB_EVENT_PATH	
          $GITHUB_GRAPHQL_URL	
          $GITHUB_HEAD_REF
          $GITHUB_JOB
          $GITHUB_PATH	
          $GITHUB_REF_NAME	
          $GITHUB_REF_PROTECTED	
          $GITHUB_REF_TYPE	
          $GITHUB_REPOSITORY	
          $GITHUB_REPOSITORY_OWNER
          $GITHUB_RETENTION_DAYS
          $GITHUB_RUN_ATTEMPT	
          $GITHUB_RUN_ID	
          $GITHUB_RUN_NUMBER	
          $GITHUB_SHA	
          $GITHUB_WORKFLOW	
          $GITHUB_WORKSPACE	
          $RUNNER_ARCH	
          $RUNNER_NAME	
          $RUNNER_OS	
          $RUNNER_TEMP	
          $RUNNER_TOOL_CACHE
        
# push  docker image
        
      #- name: Docker Image to Container Registry (GCR)
        #run: docker push $HOSTNAME/$PROJECT_ID/$IMAGE_NAME:${{ github.event.inputs.image-tag }}
        
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          channel-id: 'hello-see-log'
          # For posting a simple plain text message
          slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          

        

         
         

        
 
